In [1]:
!pip install numpy 

In [2]:
import numpy as np

In [3]:
list=[1,2,3,4]

In [4]:
type(list)

list

In [5]:
arr=np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
1
2
3
4

4

In [9]:
arr.size

4

In [10]:
z=np.zeros(10)

In [11]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
z=np.ones(10)

In [13]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#one dimensional array
o=np.array([1,2,3,4])

In [15]:
o

array([1, 2, 3, 4])

In [16]:
o.ndim

1

In [17]:
o.shape

(4,)

In [18]:
#2-d array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [19]:
x.ndim

2

In [20]:
x.shape

(4, 3)

In [21]:
#3 d array
x=x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [22]:
x.ndim

3

In [23]:
x.shape

(3, 2, 2)

In [24]:
x=x.reshape(3,4)

In [25]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

In [26]:
x.ndim

2

In [27]:
x.shape

(3, 4)

# Indexing

## Accessing 1 d array

In [28]:
arr=np.array([1,2,3,4])

In [29]:
arr[1]

2

In [30]:
arr[1]+arr[2]

5

##Accessing 2d array 

In [31]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
print("2 element in 1 st dim",arr[0,1])

2 element in 1 st dim 2


In [33]:
print("2 element in 2 st dim",arr[1,1])

2 element in 2 st dim 7


In [34]:
print("5 element in 2 st dim",arr[1,4])

5 element in 2 st dim 10


In [35]:
#linspace linspace(start,end,no of values between 0 and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#identitiy matrix
x=np.eye(3)

In [37]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
x.shape

(3, 3)

In [39]:
np.random.randint(0,50,5)

array([31, 40, 23,  6, 40])

In [40]:
np.random.rand(3,3)

array([[0.0487083 , 0.53042032, 0.32827577],
       [0.90116037, 0.99669122, 0.74127403],
       [0.25883978, 0.81140914, 0.50266926]])

In [41]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [43]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
arr.max()

10

In [45]:
arr.argmax()

9

In [46]:
arr.min()

1

In [47]:
a=np.arange(0,11,2)

## slicing

In [48]:
a

array([ 0,  2,  4,  6,  8, 10])

In [49]:
a[1:3]   #[start value:end value+1]

array([2, 4])

In [50]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [52]:
a[0:0+1,0:1+1]

array([[1, 2]])

In [53]:
a[0:1,0:2]

array([[1, 2]])

In [54]:
a[0:1,1:3]

array([[2, 3]])

In [55]:
array([[1, 2, 3],    1 st row   0
       [2, 3, 4],    2 nd row   1
       [4, 5, 6]])    3 rd row  2

       c1  c2 c3 




SyntaxError: invalid syntax. Perhaps you forgot a comma? (1222789626.py, line 1)

In [ ]:
a[2:3,0:2]

array([[4, 5]])

In [ ]:
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [ ]:
a[1:3,1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
a[1:,1:]

array([[3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [ ]:
a=np.arange(0,11,2)

In [ ]:
a

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a1=np.arange(0,11,2)

In [ ]:
c=a+a1

In [ ]:
c

array([ 0,  4,  8, 12, 16, 20])

In [ ]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [ ]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]=31

In [ ]:
arr

array([31,  2,  3,  4,  5])

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
z=arr.view()

In [ ]:
z

array([31,  2,  3,  4,  5])

In [ ]:
arr[1]=45


In [ ]:
arr

array([31, 45,  3,  4,  5])

In [ ]:
z

array([31, 45,  3,  4,  5])

In [ ]:
create an array 5 *5 whcih should contain from 0 to 24